from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
import os

NAVY = HexColor("#0f2a44")
TEXT = HexColor("#111827")
MUTED = HexColor("#4b5563")
GREEN = HexColor("#1a7f37")
AMBER = HexColor("#b45309")
RED = HexColor("#9f1239")

def generate_pdf(evaluation_id, period, overall_risk, results):
    file_path = f"reports/evaluation_{evaluation_id}.pdf"
    os.makedirs("reports", exist_ok=True)

    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph(
        "Covenant Risk Assessment Report",
        ParagraphStyle("title", fontSize=16, textColor=NAVY, spaceAfter=14)
    ))

    risk_color = GREEN if overall_risk == "LOW" else AMBER if overall_risk == "AMBER" else RED

    elements.append(Paragraph(
        f"<b>Reporting Period:</b> {period}<br/><b>Overall Risk:</b> "
        f"<font color='{risk_color.hexval()}'>{overall_risk}</font>",
        ParagraphStyle("meta", fontSize=10, textColor=TEXT, spaceAfter=16)
    ))

    table_data = [["Covenant", "Metric", "Value", "Status"]]
    for r in results:
        table_data.append([
            r["covenant_name"],
            r["metric"],
            str(r["value"]),
            r["status"]
        ])

    table = Table(table_data, colWidths=[140, 100, 80, 80])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e5e7eb")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (2, 1), (-1, -1), "CENTER")
    ]))

    elements.append(table)

    elements.append(Paragraph(
        "Generated by CovenantGuard – Internal Risk Assessment Tool",
        ParagraphStyle("footer", fontSize=8, textColor=MUTED, alignment=1, spaceBefore=20)
    ))

    doc.build(elements)
    return file_path
